#!/bin/bash
: <<__


  Called by upstart to manage mongo-express

  You'll need to modify mongo-express/node_modules/mongo-express/config.js

  line 23: comment out "password: 'pass'"
  line 28: comment out "username: 'admin'"
  line 85: change localhost to '0.0.0.0 in "host: process.env.VCAP_APP_HOST  || 'localhost'"

__

cd /home/vagrant/mongo-express

# force loading of nvm
export NVM_DIR="/home/vagrant/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm use 4
cd node_modules/mongo-express
node app.js --port '0.0.0.0:8081' >> /home/vagrant/mongo-express/logs/mongo-express.log 2>&1
